version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "change-case"
      - dependency-name: "fflate"
      - dependency-name: "gtfs-realtime-bindings"
      - dependency-name: "papaparse"
      - dependency-name: "react"
    groups:
      vite-packages:
        patterns:
          - "@vitejs/*"
          - "vite"
      vitest-packages:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "fix(deps):"
    allow:
      - dependency-name: "change-case"
      - dependency-name: "fflate"
      - dependency-name: "gtfs-realtime-bindings"
      - dependency-name: "papaparse"
      - dependency-name: "react"
