version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
      vite-packages:
        patterns:
          - "@vitejs/*"
          - "vite"
      vitest-packages:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
    commit-message:
      prefix: chore(deps)
