on:
  workflow_call:
jobs:
  oxfmt:
    name: vite
    uses: umts/.github/.github/workflows/oxfmt.yml@main
  oxlint:
    name: vite
    uses: umts/.github/.github/workflows/oxlint.yml@main
  vite:
    name: vite
    uses: umts/.github/.github/workflows/vite.yml@main
  vitest:
    name: vite
    uses: umts/.github/.github/workflows/vitest.yml@main
