on:
  workflow_call:
jobs:
  eslint:
    name: vite
    uses: umts/.github/.github/workflows/eslint.yml@main
  vite:
    name: vite
    uses: umts/.github/.github/workflows/vite.yml@main
  vitest:
    name: vite
    uses: umts/.github/.github/workflows/vitest.yml@main
